server:
  port: 8280

spring:
  application:
    name: shield-gateway
  cloud:
    gateway:
      routes:
        - id: analytics-service
          uri: lb://shield-analytics
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100

        - id: admin-service
          uri: lb://shield-admin
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 50

        - id: location-service-api
          uri: lb://shield-location
          predicates:
            - Path=/api/v1/location/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200

        - id: location-service-internal
          uri: lb://shield-location
          predicates:
            - Path=/internal/location/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 200
                redis-rate-limiter.burstCapacity: 400
