apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shield-prod

resources:
- ../../base/eureka
- ../../base/gateway
- ../../base/auth
- ../../base/tenant
- ../../base/profile
- ../../base/dns
- ../../base/location
- ../../base/notification
- ../../base/rewards
- ../../base/analytics
- ../../base/admin
- ../../base/ai
- ../../base/website
- ../../base

  # CI pipeline sets these via: kustomize edit set image REGISTRY/shield-gateway=<acr>.azurecr.io/shield-gateway:<sha>
images:
- name: REGISTRY/shield-admin
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-admin
  newTag: latest
- name: REGISTRY/shield-ai
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-ai
  newTag: latest
- name: REGISTRY/shield-analytics
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-analytics
  newTag: latest
- name: REGISTRY/shield-auth
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-auth
  newTag: latest
- name: REGISTRY/shield-dns
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-dns
  newTag: latest
- name: REGISTRY/shield-eureka
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-eureka
  newTag: latest
- name: REGISTRY/shield-gateway
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-gateway
  newTag: latest
- name: REGISTRY/shield-location
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-location
  newTag: latest
- name: REGISTRY/shield-notification
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-notification
  newTag: latest
- name: REGISTRY/shield-profile
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-profile
  newTag: latest
- name: REGISTRY/shield-rewards
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-rewards
  newTag: latest
- name: REGISTRY/shield-tenant
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-tenant
  newTag: latest
- name: REGISTRY/shield-website
  newName: shieldacrh44d4fynx4l2c.azurecr.io/shield-website
  newTag: latest

  # Prod: 2 replicas for gateway + auth
  # Prod config overrides
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shield-gateway
    spec:
      replicas: 2
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shield-auth
    spec:
      replicas: 2
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: shield-config
    data:
      LOG_LEVEL: "WARN"
      SPRING_PROFILES_ACTIVE: "kubernetes,prod"
