spring:
  application:
    name: shield-tenant

  config:
    import: optional:configserver:http://localhost:8288

  flyway:
    schemas: tenant
    table: flyway_schema_history_tenant
    locations: classpath:db/migration/tenant

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.rstglobal.shield.tenant: DEBUG
