spring:
  application:
    name: shield-tenant

  config:
    import: optional:configserver:http://localhost:8288

  datasource:
    hikari:
      maximum-pool-size: 8
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: ShieldTenantPool
      leak-detection-threshold: 60000

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  flyway:
    schemas: tenant
    table: flyway_schema_history_tenant
    locations: classpath:db/migration/tenant

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.rstglobal.shield.tenant: DEBUG
