spring:
  config:
    import: "optional:"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:2}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:true}

eureka:
  client:
    serviceUrl:
      defaultZone: http://shield-eureka:8261/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
