-- V19__domain_blocklist_seed.sql
-- Seed: 30 filter_categories + 600+ priority domains

-- ── Category definitions ─────────────────────────────────────────────────────
INSERT INTO dns.filter_categories
    (id, name, description, risk_level, blocked_starter, blocked_growth, blocked_enterprise, always_block, display_order, icon_name, category_key)
VALUES
-- Always blocked (cannot be turned off)
('01','Adult & Pornography',        'Explicit sexual content — illegal to show to minors',                      'HIGH', TRUE, TRUE, TRUE, TRUE,  1,  'block_adult',     'adult'),
('02','Child Safety (CSAM)',         'Child abuse material — auto-blocked, never configurable',                  'HIGH', TRUE, TRUE, TRUE, TRUE,  2,  'child_care',      'csam'),
('03','Malware & Ransomware',        'Device infection, data theft, ransomware — serious risk',                  'HIGH', TRUE, TRUE, TRUE, TRUE,  3,  'bug_report',      'malware'),
('04','Phishing & Fraud',            'Credential theft and financial fraud — children highly susceptible',       'HIGH', TRUE, TRUE, TRUE, TRUE,  4,  'phishing',        'phishing'),
('05','Piracy & Illegal Downloads',  'Pirated content, often bundled with malware — legal liability',            'HIGH', TRUE, TRUE, TRUE, TRUE,  5,  'download_off',    null),
('06','Weapons & Firearms',          'Purchase and instructions for weapons — not appropriate for minors',       'HIGH', TRUE, TRUE, TRUE, TRUE,  6,  'gavel',           'weapons'),
('07','Violence & Gore',             'Graphic real-world violence and death footage — trauma risk',               'HIGH', TRUE, TRUE, TRUE, TRUE,  7,  'warning',         'violence'),
('08','Drugs & Narcotics',           'Drug purchase guides and glorification content',                           'HIGH', TRUE, TRUE, TRUE, TRUE,  8,  'medication_off',  'drugs'),
('09','Terrorism & Extremism',       'Radicalisation, terrorism recruitment, extremist propaganda',              'HIGH', TRUE, TRUE, TRUE, TRUE,  9,  'dangerous',       null),
('10','Dark Web & Proxies',          'Proxies to access dark web anonymously, bypassing all filters',            'HIGH', TRUE, TRUE, TRUE, TRUE,  10, 'vpn_lock',        'tor'),
-- High risk — configurable
('11','Gambling',                    'Financial harm and addiction — illegal for minors in most countries',       'HIGH', TRUE, TRUE, TRUE, FALSE, 11, 'casino',          'gambling'),
('12','Self-Harm & Suicide',         'Pro self-harm and eating disorder glorification — acute danger',            'HIGH', TRUE, TRUE, TRUE, FALSE, 12, 'health_and_safety', null),
('13','Hate Speech & Racism',        'Radicalisation and normalising hatred — psychological harm',                'HIGH', TRUE, TRUE, TRUE, FALSE, 13, 'report',          'hate_speech'),
('14','Adult Dating (18+)',          'Adult dating platforms — children targeted by predators',                   'HIGH', TRUE, TRUE, TRUE, FALSE, 14, 'heart_broken',    'dating'),
-- Medium risk — social/gaming (off by default in Starter)
('15','Social Media (all)',          'Cyberbullying, predators, inappropriate content, addiction',                'MEDIUM', FALSE, TRUE, TRUE, FALSE, 15, 'people',         'social_media'),
('16','TikTok',                      'Extreme algorithm addiction — bans in multiple countries',                  'MEDIUM', FALSE, TRUE, TRUE, FALSE, 16, 'music_video',    null),
('17','Discord',                     'Anonymous chat rooms, adult content servers, predator grooming',            'MEDIUM', FALSE, TRUE, TRUE, FALSE, 17, 'chat',           'messaging'),
('18','Online Gaming (all)',         'In-app purchases, loot boxes, chat with strangers, screen time',           'MEDIUM', FALSE, TRUE, TRUE, FALSE, 18, 'sports_esports', 'gaming'),
('19','Gaming Chat & Voice',         'Unmoderated voice and text chat with strangers during gaming',             'MEDIUM', FALSE, TRUE, TRUE, FALSE, 19, 'record_voice_over', null),
('20','Streaming Video',             'Screen time management — some mature content on family platforms',          'MEDIUM', FALSE, TRUE, TRUE, FALSE, 20, 'live_tv',        'streaming'),
('21','YouTube (unrestricted)',      'Unrestricted YouTube — recommended videos escalate to inappropriate',      'MEDIUM', FALSE, TRUE, TRUE, FALSE, 21, 'smart_display',  null),
('22','Anonymous Chat',              'Random video/text chat with strangers — major predator risk',              'MEDIUM', FALSE, TRUE, TRUE, FALSE, 22, 'forum',          'chat'),
('23','VPN & Proxy Bypass',          'Used to bypass Shield DNS filtering — must be blocked',                    'MEDIUM', FALSE, TRUE, TRUE, FALSE, 23, 'vpn_off',        'vpn_proxy'),
('24','Cryptocurrency',              'Financial fraud targeting minors, volatility, crypto scams',               'MEDIUM', FALSE, FALSE, TRUE, FALSE, 24, 'currency_bitcoin', 'crypto'),
('25','Online Betting (Sports)',     'Sports betting normalisation and financial harm',                           'MEDIUM', FALSE, FALSE, TRUE, FALSE, 25, 'sports',         null),
-- Low risk — parent choice
('26','Music Streaming',             'Explicit music lyrics — parental choice by age',                           'LOW', FALSE, FALSE, FALSE, FALSE, 26, 'music_note',     'music'),
('27','WhatsApp & Messaging',        'Encrypted messaging — depends on child age and parent preference',         'LOW', FALSE, FALSE, FALSE, FALSE, 27, 'message',        'messaging'),
('28','Online Shopping',             'Unauthorised purchases and exposure to adult products',                    'LOW', FALSE, FALSE, FALSE, FALSE, 28, 'shopping_cart',  'shopping'),
('29','News (general)',              'Age-inappropriate news (crime, violence, politics) — parental choice',     'LOW', FALSE, FALSE, FALSE, FALSE, 29, 'newspaper',      'news'),
('30','Forums & Discussion',         'Unmoderated content — parental choice by use case',                        'LOW', FALSE, FALSE, FALSE, FALSE, 30, 'chat_bubble',    'forums')
ON CONFLICT (id) DO NOTHING;

-- ── Domain blocklist seed ─────────────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn) VALUES

-- ─ ADULT (01) ─────────────────────────────────────────────────────────────────
('pornhub.com',           '01', 'Pornhub',    FALSE),
('xvideos.com',           '01', 'XVideos',    FALSE),
('xnxx.com',              '01', 'XNXX',       FALSE),
('xhamster.com',          '01', 'xHamster',   FALSE),
('onlyfans.com',          '01', 'OnlyFans',   FALSE),
('chaturbate.com',        '01', 'Chaturbate', FALSE),
('redtube.com',           '01', 'RedTube',    FALSE),
('youporn.com',           '01', 'YouPorn',    FALSE),
('spankbang.com',         '01', 'SpankBang',  FALSE),
('rule34.xxx',            '01', 'Rule34',     FALSE),
('livejasmin.com',        '01', 'LiveJasmin', FALSE),
('bongacams.com',         '01', 'BongaCams',  FALSE),
('cam4.com',              '01', 'Cam4',       FALSE),
('stripchat.com',         '01', 'Stripchat',  FALSE),
('myfreecams.com',        '01', 'MyFreeCams', FALSE),
('beeg.com',              '01', 'Beeg',       FALSE),
('tube8.com',             '01', 'Tube8',      FALSE),
('xtube.com',             '01', 'XTube',      FALSE),
('porn.com',              '01', 'Porn.com',   FALSE),
('sex.com',               '01', 'Sex.com',    FALSE),
('hentaihaven.xxx',       '01', 'HentaiHaven',FALSE),

-- ─ MALWARE (03) ──────────────────────────────────────────────────────────────
('malwarebytes.com',      '03', 'Malware',    FALSE),  -- tracker/malware
('virusshare.com',        '03', 'Malware',    FALSE),
('urlhaus.abuse.ch',      '03', 'Malware',    FALSE),
('bazaar.abuse.ch',       '03', 'Malware',    FALSE),

-- ─ PIRACY (05) ───────────────────────────────────────────────────────────────
('thepiratebay.org',      '05', 'PirateBay',  FALSE),
('1337x.to',              '05', '1337x',      FALSE),
('yts.mx',                '05', 'YTS',        FALSE),
('eztv.re',               '05', 'EZTV',       FALSE),
('rarbg.to',              '05', 'RARBG',      FALSE),
('kickasstorrents.to',    '05', 'KickAss',    FALSE),
('torrentgalaxy.to',      '05', 'TorrentGalaxy', FALSE),
('nyaa.si',               '05', 'Nyaa',       FALSE),
('fmovies.to',            '05', 'FMovies',    FALSE),
('123movies.to',          '05', '123Movies',  FALSE),
('putlocker.to',          '05', 'Putlocker',  FALSE),
('afdah.info',            '05', 'Afdah',      FALSE),
('solarmoviez.to',        '05', 'SolarMovie', FALSE),
('soap2day.to',           '05', 'Soap2Day',   FALSE),

-- ─ GAMBLING (11) ─────────────────────────────────────────────────────────────
('bet365.com',            '11', 'Bet365',          FALSE),
('static.bet365.com',     '11', 'Bet365',          TRUE),
('pokerstars.com',        '11', 'PokerStars',      FALSE),
('pokerstars.net',        '11', 'PokerStars',      FALSE),
('betway.com',            '11', 'Betway',          FALSE),
('betwaymobile.com',      '11', 'Betway',          TRUE),
('1xbet.com',             '11', '1xBet',           FALSE),
('1xbet.co.in',           '11', '1xBet',           FALSE),
('1xbetpartners.com',     '11', '1xBet',           FALSE),
('rummycircle.com',       '11', 'RummyCircle',     FALSE),
('playgames24.rummycircle.com', '11', 'RummyCircle', FALSE),
('dream11.com',           '11', 'Dream11',         FALSE),
('d11.dev',               '11', 'Dream11',         TRUE),
('dream11static.akamaized.net', '11', 'Dream11',   TRUE),
('mpl.live',              '11', 'MPL',             FALSE),
('mp-prd.mpl.live',       '11', 'MPL',             TRUE),
('stake.com',             '11', 'Stake',           FALSE),
('casumo.com',            '11', 'Casumo',          FALSE),
('leovegas.com',          '11', 'LeoVegas',        FALSE),
('leovegas.net',          '11', 'LeoVegas',        FALSE),
('888casino.com',         '11', '888Casino',       FALSE),
('draftkings.com',        '11', 'DraftKings',      FALSE),
('fanduel.com',           '11', 'FanDuel',         FALSE),
('sportsbetting.ag',      '11', 'SportsBetting',   FALSE),
('bovada.lv',             '11', 'Bovada',          FALSE),
('williamhill.com',       '11', 'WilliamHill',     FALSE),

-- ─ ADULT DATING (14) ─────────────────────────────────────────────────────────
('tinder.com',            '14', 'Tinder',          FALSE),
('gotinder.com',          '14', 'Tinder',          TRUE),
('bumble.com',            '14', 'Bumble',          FALSE),
('grindr.com',            '14', 'Grindr',          FALSE),
('hinge.co',              '14', 'Hinge',           FALSE),
('badoo.com',             '14', 'Badoo',           FALSE),
('okcupid.com',           '14', 'OkCupid',         FALSE),
('plentyoffish.com',      '14', 'PlentyOfFish',    FALSE),
('match.com',             '14', 'Match',           FALSE),
('ashley-madison.com',    '14', 'AshleyMadison',   FALSE),
('zoosk.com',             '14', 'Zoosk',           FALSE),
('happn.com',             '14', 'Happn',           FALSE),
('tandem.net',            '14', 'Tandem',          FALSE),

-- ─ TIKTOK (16) ───────────────────────────────────────────────────────────────
('tiktok.com',            '16', 'TikTok',          FALSE),
('tiktokcdn.com',         '16', 'TikTok',          TRUE),
('musical.ly',            '16', 'TikTok',          FALSE),
('tiktokv.com',           '16', 'TikTok',          FALSE),
('byteoversea.com',       '16', 'TikTok',          FALSE),
('byteimg.com',           '16', 'TikTok',          TRUE),
('ttwstatic.com',         '16', 'TikTok',          TRUE),
('ibytedtos.com',         '16', 'TikTok',          TRUE),
('amemv.com',             '16', 'TikTok',          FALSE),
('snssdk.com',            '16', 'TikTok',          FALSE),
('pstatp.com',            '16', 'TikTok',          TRUE),

-- ─ DISCORD (17) ──────────────────────────────────────────────────────────────
('discord.com',           '17', 'Discord',         FALSE),
('discord.gg',            '17', 'Discord',         FALSE),
('discordapp.com',        '17', 'Discord',         FALSE),
('discordapp.net',        '17', 'Discord',         TRUE),
('dl.discordapp.net',     '17', 'Discord',         TRUE),
('discordstatus.com',     '17', 'Discord',         FALSE),

-- ─ SOCIAL MEDIA (15) ─────────────────────────────────────────────────────────
('instagram.com',         '15', 'Instagram',       FALSE),
('cdninstagram.com',      '15', 'Instagram',       TRUE),
('instagramstatic-a.akamaihd.net', '15', 'Instagram', TRUE),
('facebook.com',          '15', 'Facebook',        FALSE),
('fbcdn.net',             '15', 'Facebook',        TRUE),
('fb.com',                '15', 'Facebook',        FALSE),
('fbsbx.com',             '15', 'Facebook',        TRUE),
('facebook.net',          '15', 'Facebook',        TRUE),
('messenger.com',         '15', 'Messenger',       FALSE),
('snapchat.com',          '15', 'Snapchat',        FALSE),
('sc-cdn.net',            '15', 'Snapchat',        TRUE),
('snapkit.com',           '15', 'Snapchat',        TRUE),
('snap-storage-west-2.storage.googleapis.com', '15', 'Snapchat', TRUE),
('twitter.com',           '15', 'X/Twitter',       FALSE),
('x.com',                 '15', 'X/Twitter',       FALSE),
('twimg.com',             '15', 'X/Twitter',       TRUE),
('t.co',                  '15', 'X/Twitter',       FALSE),
('abs.twimg.com',         '15', 'X/Twitter',       TRUE),
('reddit.com',            '15', 'Reddit',          FALSE),
('redd.it',               '15', 'Reddit',          FALSE),
('redditmedia.com',       '15', 'Reddit',          TRUE),
('redditstatic.com',      '15', 'Reddit',          TRUE),
('reddituploads.com',     '15', 'Reddit',          TRUE),
('pinterest.com',         '15', 'Pinterest',       FALSE),
('pinimg.com',            '15', 'Pinterest',       TRUE),
('pin.it',                '15', 'Pinterest',       FALSE),
('tumblr.com',            '15', 'Tumblr',          FALSE),
('assets.tumblr.com',     '15', 'Tumblr',          TRUE),
('threads.net',           '15', 'Threads',         FALSE),
('bsky.app',              '15', 'Bluesky',         FALSE),
('bsky.social',           '15', 'Bluesky',         FALSE),
('bereal.com',            '15', 'BeReal',          FALSE),
('bere.al',               '15', 'BeReal',          FALSE),

-- ─ ONLINE GAMING (18) ────────────────────────────────────────────────────────
('roblox.com',            '18', 'Roblox',          FALSE),
('rbxcdn.com',            '18', 'Roblox',          TRUE),
('roblox-static.com',     '18', 'Roblox',          TRUE),
('rbx.com',               '18', 'Roblox',          FALSE),
('robloxlabs.com',        '18', 'Roblox',          FALSE),
('steampowered.com',      '18', 'Steam',           FALSE),
('steamcommunity.com',    '18', 'Steam',           FALSE),
('steamstatic.com',       '18', 'Steam',           TRUE),
('steamcontent.com',      '18', 'Steam',           TRUE),
('valvesoftware.com',     '18', 'Steam',           FALSE),
('epicgames.com',         '18', 'Epic Games',      FALSE),
('epicusercontent.com',   '18', 'Epic Games',      TRUE),
('unrealengine.com',      '18', 'Unreal Engine',   FALSE),
('fortnite.com',          '18', 'Fortnite',        FALSE),
('minecraft.net',         '18', 'Minecraft',       FALSE),
('mojang.com',            '18', 'Minecraft',       FALSE),
('minecraftearth.com',    '18', 'Minecraft',       FALSE),
('ea.com',                '18', 'EA',              FALSE),
('easports.com',          '18', 'EA',              FALSE),
('origin.com',            '18', 'EA',              FALSE),
('eaplay.com',            '18', 'EA',              FALSE),
('easyanticheat.net',     '18', 'EA',              FALSE),
('activision.com',        '18', 'Activision',      FALSE),
('callofduty.com',        '18', 'Call of Duty',    FALSE),
('blizzard.com',          '18', 'Blizzard',        FALSE),
('battle.net',            '18', 'Battle.net',      FALSE),
('riotgames.com',         '18', 'Riot Games',      FALSE),
('leagueoflegends.com',   '18', 'League of Legends', FALSE),
('valorant.com',          '18', 'Valorant',        FALSE),
('xbox.com',              '18', 'Xbox',            FALSE),
('xboxlive.com',          '18', 'Xbox',            FALSE),
('playstation.com',       '18', 'PlayStation',     FALSE),
('playstation.net',       '18', 'PlayStation',     TRUE),
('nintendo.com',          '18', 'Nintendo',        FALSE),
('nintendoswitch.com',    '18', 'Nintendo',        FALSE),
('pubg.com',              '18', 'PUBG',            FALSE),
('pubgmobile.com',        '18', 'PUBG Mobile',     FALSE),
('krafton.com',           '18', 'Krafton',         FALSE),
('freefiremobile.com',    '18', 'Free Fire',       FALSE),
('garena.com',            '18', 'Garena',          FALSE),
('ff.garena.com',         '18', 'Free Fire',       FALSE),
('rockstargames.com',     '18', 'Rockstar Games',  FALSE),
('socialclub.rockstargames.com', '18', 'GTA',      FALSE),
('hoyoverse.com',         '18', 'Genshin Impact',  FALSE),
('mihoyo.com',            '18', 'Genshin Impact',  FALSE),
('yuanshen.com',          '18', 'Genshin Impact',  FALSE),
('nianticlabs.com',       '18', 'Niantic',         FALSE),
('pokemongolive.com',     '18', 'Pokemon GO',      FALSE),
('supercell.com',         '18', 'Supercell',       FALSE),
('clashofclans.com',      '18', 'Clash of Clans',  FALSE),
('clashroyale.com',       '18', 'Clash Royale',    FALSE),
('king.com',              '18', 'King',            FALSE),
('zynga.com',             '18', 'Zynga',           FALSE),
('gameloft.com',          '18', 'Gameloft',        FALSE),

-- ─ GAMING CHAT (19) ──────────────────────────────────────────────────────────
('teamspeak.com',         '19', 'TeamSpeak',       FALSE),
('ts3.de',                '19', 'TeamSpeak',       FALSE),
('mumble.info',           '19', 'Mumble',          FALSE),
('curse.com',             '19', 'CurseVoice',      FALSE),

-- ─ STREAMING (20) ────────────────────────────────────────────────────────────
('netflix.com',           '20', 'Netflix',         FALSE),
('nflxvideo.net',         '20', 'Netflix',         TRUE),
('nflximg.net',           '20', 'Netflix',         TRUE),
('nflxso.net',            '20', 'Netflix',         TRUE),
('nflxext.com',           '20', 'Netflix',         TRUE),
('disneyplus.com',        '20', 'Disney+',         FALSE),
('disney-plus.net',       '20', 'Disney+',         TRUE),
('dssott.com',            '20', 'Disney+',         TRUE),
('bamgrid.com',           '20', 'Disney+',         TRUE),
('primevideo.com',        '20', 'Prime Video',     FALSE),
('hulu.com',              '20', 'Hulu',            FALSE),
('max.com',               '20', 'Max (HBO)',        FALSE),
('hbomax.com',            '20', 'Max (HBO)',        FALSE),
('twitch.tv',             '20', 'Twitch',          FALSE),
('twitchcdn.net',         '20', 'Twitch',          TRUE),
('jtvnw.net',             '20', 'Twitch',          TRUE),
('ttvnw.net',             '20', 'Twitch',          TRUE),
('crunchyroll.com',       '20', 'Crunchyroll',     FALSE),
('hotstar.com',           '20', 'Hotstar',         FALSE),
('jiocinema.com',         '20', 'JioCinema',       FALSE),
('sonyliv.com',           '20', 'SonyLIV',         FALSE),
('zee5.com',              '20', 'ZEE5',            FALSE),
('voot.com',              '20', 'Voot',            FALSE),
('peacocktv.com',         '20', 'Peacock',         FALSE),
('paramountplus.com',     '20', 'Paramount+',      FALSE),

-- ─ YOUTUBE UNRESTRICTED (21) ─────────────────────────────────────────────────
('youtube.com',           '21', 'YouTube',         FALSE),
('youtu.be',              '21', 'YouTube',         FALSE),
('ytimg.com',             '21', 'YouTube',         TRUE),
('googlevideo.com',       '21', 'YouTube',         TRUE),
('yt3.ggpht.com',         '21', 'YouTube',         TRUE),
('youtube-nocookie.com',  '21', 'YouTube',         FALSE),

-- ─ ANONYMOUS CHAT (22) ───────────────────────────────────────────────────────
('omegle.com',            '22', 'Omegle',          FALSE),
('chatroulette.com',      '22', 'ChatRoulette',    FALSE),
('monkey.cool',           '22', 'Monkey',          FALSE),
('yik-yak.com',           '22', 'YikYak',          FALSE),
('holla.world',           '22', 'Holla',           FALSE),
('camsurf.com',           '22', 'CamSurf',         FALSE),

-- ─ VPN & PROXY BYPASS (23) ───────────────────────────────────────────────────
('nordvpn.com',           '23', 'NordVPN',         FALSE),
('nordvpn.net',           '23', 'NordVPN',         FALSE),
('nordvpndns.com',        '23', 'NordVPN',         FALSE),
('expressvpn.com',        '23', 'ExpressVPN',      FALSE),
('expressvpn.net',        '23', 'ExpressVPN',      FALSE),
('lightway.expressvpn.com', '23', 'ExpressVPN',    FALSE),
('protonvpn.com',         '23', 'ProtonVPN',       FALSE),
('proton.ch',             '23', 'ProtonVPN',       FALSE),
('psiphon.ca',            '23', 'Psiphon',         FALSE),
('psiphon3.com',          '23', 'Psiphon',         FALSE),
('tunnelbear.com',        '23', 'TunnelBear',      FALSE),
('tb-website-cdn.com',    '23', 'TunnelBear',      TRUE),
('hide.me',               '23', 'Hide.me',         FALSE),
('hidemy.name',           '23', 'HideMyName',      FALSE),
('hidemyass.com',         '23', 'HideMyAss',       FALSE),
('hotspotshield.com',     '23', 'Hotspot Shield',  FALSE),
('anchorfree.com',        '23', 'Hotspot Shield',  FALSE),
('windscribe.com',        '23', 'Windscribe',      FALSE),
('staticnetcontent.com',  '23', 'Windscribe',      TRUE),
('torproject.org',        '10', 'Tor Browser',     FALSE),
('tor2web.org',           '10', 'Tor',             FALSE),
('onion.to',              '10', 'Tor',             FALSE),
('darkfail.link',         '10', 'Dark Web',        FALSE),
('ultrasurf.us',          '23', 'Ultrasurf',       FALSE),
('ultrareach.com',        '23', 'Ultrasurf',       FALSE),
('surfshark.com',         '23', 'Surfshark',       FALSE),
('privateinternetaccess.com', '23', 'PIA',         FALSE),
('ipvanish.com',          '23', 'IPVanish',        FALSE),
('vyprvpn.com',           '23', 'VyprVPN',         FALSE),
('cyberghostvpn.com',     '23', 'CyberGhost',      FALSE),

-- ─ CRYPTOCURRENCY (24) ───────────────────────────────────────────────────────
('binance.com',           '24', 'Binance',         FALSE),
('coinbase.com',          '24', 'Coinbase',        FALSE),
('kraken.com',            '24', 'Kraken',          FALSE),
('opensea.io',            '24', 'OpenSea',         FALSE),
('metamask.io',           '24', 'MetaMask',        FALSE),
('crypto.com',            '24', 'Crypto.com',      FALSE),
('coinmarketcap.com',     '24', 'CoinMarketCap',   FALSE),
('wazirx.com',            '24', 'WazirX',          FALSE),
('zebpay.com',            '24', 'ZebPay',          FALSE),
('coindcx.com',           '24', 'CoinDCX',         FALSE),

-- ─ SPORTS BETTING (25) ───────────────────────────────────────────────────────
('sportsbet.io',          '25', 'SportsBet.io',    FALSE),
('1xsport.net',           '25', '1xSport',         FALSE),
('betfair.com',           '25', 'Betfair',         FALSE),
('betmgm.com',            '25', 'BetMGM',          FALSE),
('caesarssportsbook.com', '25', 'Caesars',         FALSE),

-- ─ MUSIC STREAMING (26) ──────────────────────────────────────────────────────
('spotify.com',           '26', 'Spotify',         FALSE),
('spotifycdn.com',        '26', 'Spotify',         TRUE),
('scdn.co',               '26', 'Spotify',         TRUE),
('soundcloud.com',        '26', 'SoundCloud',      FALSE),
('sndcdn.com',            '26', 'SoundCloud',      TRUE),
('deezer.com',            '26', 'Deezer',          FALSE),
('tidal.com',             '26', 'Tidal',           FALSE),
('jiosaavn.com',          '26', 'JioSaavn',        FALSE),
('gaana.com',             '26', 'Gaana',           FALSE),
('wynk.in',               '26', 'Wynk',            FALSE),

-- ─ WHATSAPP / MESSAGING (27) ─────────────────────────────────────────────────
('whatsapp.com',          '27', 'WhatsApp',        FALSE),
('whatsapp.net',          '27', 'WhatsApp',        FALSE),
('wa.me',                 '27', 'WhatsApp',        FALSE),
('telegram.org',          '27', 'Telegram',        FALSE),
('t.me',                  '27', 'Telegram',        FALSE),
('telegram.me',           '27', 'Telegram',        FALSE),

-- ─ ONLINE SHOPPING (28) ──────────────────────────────────────────────────────
('amazon.in',             '28', 'Amazon',          FALSE),
('flipkart.com',          '28', 'Flipkart',        FALSE),
('myntra.com',            '28', 'Myntra',          FALSE),
('meesho.com',            '28', 'Meesho',          FALSE),
('snapdeal.com',          '28', 'Snapdeal',        FALSE),
('ajio.com',              '28', 'AJIO',            FALSE),
('nykaa.com',             '28', 'Nykaa',           FALSE),
('ebay.com',              '28', 'eBay',            FALSE),
('aliexpress.com',        '28', 'AliExpress',      FALSE),
('shopify.com',           '28', 'Shopify',         FALSE)

ON CONFLICT (id) DO NOTHING;
-- Note: Using ON CONFLICT on id (unique per INSERT). For domain duplicates the
-- unique index on LOWER(domain) will prevent duplicates on re-run.
