-- V24__domain_blocklist_20k.sql
-- Extended domain blocklist: additional high-confidence domains across all categories.
-- Source column already exists (added in V18). V19 seeded ~300 domains.
-- This migration adds ~500 more curated domains with ON CONFLICT DO NOTHING.

-- ── ADULT (01) ─────────────────────────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('brazzers.com',          '01', 'Brazzers',        FALSE, 'curated'),
('naughtyamerica.com',    '01', 'NaughtyAmerica',  FALSE, 'curated'),
('mofos.com',             '01', 'Mofos',           FALSE, 'curated'),
('realitykings.com',      '01', 'RealityKings',    FALSE, 'curated'),
('bangbros.com',          '01', 'BangBros',        FALSE, 'curated'),
('fakehub.com',           '01', 'FakeHub',         FALSE, 'curated'),
('digitalplayground.com', '01', 'DigitalPlayground',FALSE,'curated'),
('kink.com',              '01', 'Kink',            FALSE, 'curated'),
('manwin.com',            '01', 'Manwin',          FALSE, 'curated'),
('mindgeek.com',          '01', 'MindGeek',        FALSE, 'curated'),
('trafficjunky.net',      '01', 'TrafficJunky',    FALSE, 'curated'),
('thumbzilla.com',        '01', 'Thumbzilla',      FALSE, 'curated'),
('hardsextube.com',       '01', 'HardSexTube',     FALSE, 'curated'),
('gotporn.com',           '01', 'GotPorn',         FALSE, 'curated'),
('drtuber.com',           '01', 'DrTuber',         FALSE, 'curated'),
('hdporn.net',            '01', 'HDPorn',          FALSE, 'curated'),
('porntrex.com',          '01', 'PornTrex',        FALSE, 'curated'),
('fuq.com',               '01', 'Fuq',             FALSE, 'curated'),
('faphouse.com',          '01', 'FapHouse',        FALSE, 'curated'),
('nurugallery.com',       '01', 'NuruGallery',     FALSE, 'curated'),
('hclips.com',            '01', 'HClips',          FALSE, 'curated'),
('xmoviesforyou.com',     '01', 'XMoviesForYou',   FALSE, 'curated'),
('pornhd.com',            '01', 'PornHD',          FALSE, 'curated'),
('yobt.tv',               '01', 'Yobt',            FALSE, 'curated'),
('sexvid.xxx',            '01', 'SexVid',          FALSE, 'curated'),
('nuvid.com',             '01', 'Nuvid',           FALSE, 'curated'),
('upornia.com',           '01', 'Upornia',         FALSE, 'curated'),
('cliphunter.com',        '01', 'ClipHunter',      FALSE, 'curated'),
('definebabe.com',        '01', 'DefineBabe',      FALSE, 'curated'),
('tnaflix.com',           '01', 'TNAFlix',         FALSE, 'curated'),
('vporn.com',             '01', 'vPorn',           FALSE, 'curated'),
('sextube.com',           '01', 'SexTube',         FALSE, 'curated'),
('slutload.com',          '01', 'SlutLoad',        FALSE, 'curated'),
('pornerbros.com',        '01', 'PornerBros',      FALSE, 'curated'),
('sexu.com',              '01', 'Sexu',            FALSE, 'curated'),
('4tube.com',             '01', '4Tube',           FALSE, 'curated'),
('homemoviestube.com',    '01', 'HomeMoviesTube',  FALSE, 'curated'),
('empflix.com',           '01', 'EmpFlix',         FALSE, 'curated'),
('videosz.com',           '01', 'VideosZ',         FALSE, 'curated'),
('pornoxo.com',           '01', 'PornoXO',         FALSE, 'curated'),
('sex3.com',              '01', 'Sex3',            FALSE, 'curated'),
('9taxi.com',             '01', '9Taxi',           FALSE, 'curated'),
('xxxbunker.com',         '01', 'XXXBunker',       FALSE, 'curated'),
('moviefap.com',          '01', 'MovieFap',        FALSE, 'curated'),
('vjav.com',              '01', 'vJav',            FALSE, 'curated'),
('javhd.com',             '01', 'JavHD',           FALSE, 'curated'),
('dmm.co.jp',             '01', 'DMM',             FALSE, 'curated'),
('fc2.com',               '01', 'FC2 Adult',       FALSE, 'curated'),
('caribbeancom.com',      '01', 'Caribbean',       FALSE, 'curated'),
('jav.guru',              '01', 'JAV Guru',        FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── MALWARE / PHISHING (03 / 04) ──────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
-- Malware C2 / dropper domains (03)
('downloadme.net',          '03', 'Malware',  FALSE, 'curated'),
('clickndownload.com',      '03', 'Malware',  FALSE, 'curated'),
('softonic-ads.com',        '03', 'Malware',  FALSE, 'curated'),
('conduit.com',             '03', 'Malware',  FALSE, 'curated'),
('sweetpacks.com',          '03', 'Malware',  FALSE, 'curated'),
('snapdo.com',              '03', 'Malware',  FALSE, 'curated'),
('search.protect.com',      '03', 'Malware',  FALSE, 'curated'),
('isearch.avg.com',         '03', 'Malware',  FALSE, 'curated'),
('myway.com',               '03', 'Adware',   FALSE, 'curated'),
('mywebsearch.com',         '03', 'Adware',   FALSE, 'curated'),
('sprotect.net',            '03', 'Malware',  FALSE, 'curated'),
('infospace.com',           '03', 'Adware',   FALSE, 'curated'),
('funmoods.com',            '03', 'Malware',  FALSE, 'curated'),
('delta-search.com',        '03', 'Malware',  FALSE, 'curated'),
('dealply.com',             '03', 'Adware',   FALSE, 'curated'),
('superfish.com',           '03', 'Adware',   FALSE, 'curated'),
('istart.webssearches.com', '03', 'Malware',  FALSE, 'curated'),
('dosearches.com',          '03', 'Malware',  FALSE, 'curated'),
('taplika.com',             '03', 'Malware',  FALSE, 'curated'),
('webssearches.com',        '03', 'Malware',  FALSE, 'curated'),
-- Phishing domains (04)
('paypa1.com',              '04', 'Phishing', FALSE, 'curated'),
('paypai.com',              '04', 'Phishing', FALSE, 'curated'),
('secure-paypal.com',       '04', 'Phishing', FALSE, 'curated'),
('appleid-verify.com',      '04', 'Phishing', FALSE, 'curated'),
('apple-account-verify.com','04', 'Phishing', FALSE, 'curated'),
('microsoft-alert.com',     '04', 'Phishing', FALSE, 'curated'),
('amazon-security.net',     '04', 'Phishing', FALSE, 'curated'),
('amazon-account-verify.com','04','Phishing', FALSE, 'curated'),
('google-support-help.com', '04', 'Phishing', FALSE, 'curated'),
('g00gle.com',              '04', 'Phishing', FALSE, 'curated'),
('facebooklogin.net',       '04', 'Phishing', FALSE, 'curated'),
('facebook-login.org',      '04', 'Phishing', FALSE, 'curated'),
('instagram-login.net',     '04', 'Phishing', FALSE, 'curated'),
('netflixlogin.net',        '04', 'Phishing', FALSE, 'curated'),
('netflix-billing.com',     '04', 'Phishing', FALSE, 'curated'),
('bankofamerica-secure.com','04', 'Phishing', FALSE, 'curated'),
('chase-secure-login.com',  '04', 'Phishing', FALSE, 'curated'),
('wellsfargo-security.com', '04', 'Phishing', FALSE, 'curated'),
('sbibankindia.net',        '04', 'Phishing', FALSE, 'curated'),
('hdfcbank-verify.com',     '04', 'Phishing', FALSE, 'curated'),
('idfcfirstbank-kyc.com',   '04', 'Phishing', FALSE, 'curated'),
('icicibank-update.com',    '04', 'Phishing', FALSE, 'curated'),
('paytm-wallet.org',        '04', 'Phishing', FALSE, 'curated'),
('phonepay-upi.com',        '04', 'Phishing', FALSE, 'curated'),
('gpay-cashback.com',       '04', 'Phishing', FALSE, 'curated'),
('update-adobe-flash.com',  '04', 'Phishing', FALSE, 'curated'),
('win10-update.net',        '04', 'Phishing', FALSE, 'curated'),
('your-device-infected.com','04', 'Phishing', FALSE, 'curated'),
('tech-support-alert.com',  '04', 'Phishing', FALSE, 'curated'),
('irs-refund-gov.com',      '04', 'Phishing', FALSE, 'curated'),
('covid19-relief-fund.com', '04', 'Phishing', FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── GAMBLING (11) ─────────────────────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('betonline.ag',            '11', 'BetOnline',       FALSE, 'curated'),
('mybet.com',               '11', 'MyBet',           FALSE, 'curated'),
('ladbrokes.com',           '11', 'Ladbrokes',       FALSE, 'curated'),
('coral.co.uk',             '11', 'Coral',           FALSE, 'curated'),
('paddypower.com',          '11', 'PaddyPower',      FALSE, 'curated'),
('skybet.com',              '11', 'SkyBet',          FALSE, 'curated'),
('betvictor.com',           '11', 'BetVictor',       FALSE, 'curated'),
('unibet.com',              '11', 'Unibet',          FALSE, 'curated'),
('bwin.com',                '11', 'bwin',            FALSE, 'curated'),
('partypoker.com',          '11', 'PartyPoker',      FALSE, 'curated'),
('888poker.com',            '11', '888Poker',        FALSE, 'curated'),
('worldpokerclub.com',      '11', 'WorldPokerClub',  FALSE, 'curated'),
('adda52.com',              '11', 'Adda52',          FALSE, 'curated'),
('pokerbaazi.com',          '11', 'PokerBaazi',      FALSE, 'curated'),
('spartan-poker.com',       '11', 'SpartanPoker',    FALSE, 'curated'),
('junglee-rummy.com',       '11', 'JungleeRummy',    FALSE, 'curated'),
('jeetwin.com',             '11', 'JeetWin',         FALSE, 'curated'),
('parimatch.com',           '11', 'Parimatch',       FALSE, 'curated'),
('mostbet.com',             '11', 'MostBet',         FALSE, 'curated'),
('10cric.com',              '11', '10CRIC',          FALSE, 'curated'),
('betway.in',               '11', 'Betway',          FALSE, 'curated'),
('dafabet.com',             '11', 'Dafabet',         FALSE, 'curated'),
('22bet.com',               '11', '22Bet',           FALSE, 'curated'),
('melbet.com',              '11', 'MelBet',          FALSE, 'curated'),
('fun88.com',               '11', 'Fun88',           FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── SOCIAL MEDIA (15) ─────────────────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('vk.com',                  '15', 'VKontakte',       FALSE, 'curated'),
('vkontakte.ru',            '15', 'VKontakte',       FALSE, 'curated'),
('ok.ru',                   '15', 'Odnoklassniki',   FALSE, 'curated'),
('weibo.com',               '15', 'Weibo',           FALSE, 'curated'),
('wechat.com',              '15', 'WeChat',          FALSE, 'curated'),
('line.me',                 '15', 'LINE',            FALSE, 'curated'),
('kik.com',                 '15', 'Kik',             FALSE, 'curated'),
('likee.video',             '15', 'Likee',           FALSE, 'curated'),
('moj.tv',                  '15', 'Moj',             FALSE, 'curated'),
('sharechat.com',           '15', 'ShareChat',       FALSE, 'curated'),
('meesho.com',              '15', 'Meesho Social',   FALSE, 'curated'),
('chingari.io',             '15', 'Chingari',        FALSE, 'curated'),
('josh.app',                '15', 'Josh',            FALSE, 'curated'),
('mx.takatak.tv',           '15', 'TakaTak',         FALSE, 'curated'),
('roposo.com',              '15', 'Roposo',          FALSE, 'curated'),
('clubhouse.com',           '15', 'Clubhouse',       FALSE, 'curated'),
('lemon8-app.com',          '15', 'Lemon8',          FALSE, 'curated'),
('mastodon.social',         '15', 'Mastodon',        FALSE, 'curated'),
('truth.social',            '15', 'TruthSocial',     FALSE, 'curated'),
('parler.com',              '15', 'Parler',          FALSE, 'curated'),
('gettr.com',               '15', 'GETTR',           FALSE, 'curated'),
('gab.com',                 '15', 'Gab',             FALSE, 'curated'),
('mix.com',                 '15', 'Mix',             FALSE, 'curated'),
('digg.com',                '15', 'Digg',            FALSE, 'curated'),
('stumbleupon.com',         '15', 'StumbleUpon',     FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── ONLINE GAMING (18) ────────────────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('2game.com',               '18', '2Game',           FALSE, 'curated'),
('gog.com',                 '18', 'GOG',             FALSE, 'curated'),
('gogalaxy.com',            '18', 'GOG Galaxy',      FALSE, 'curated'),
('ubisoft.com',             '18', 'Ubisoft',         FALSE, 'curated'),
('ubisoftstatic.com',       '18', 'Ubisoft',         TRUE,  'curated'),
('ubi.com',                 '18', 'Ubisoft',         FALSE, 'curated'),
('bethesda.net',            '18', 'Bethesda',        FALSE, 'curated'),
('zenimax.com',             '18', 'ZeniMax',         FALSE, 'curated'),
('2k.com',                  '18', '2K Games',        FALSE, 'curated'),
('squareenix.com',          '18', 'Square Enix',     FALSE, 'curated'),
('finalfantasyxiv.com',     '18', 'FFXIV',           FALSE, 'curated'),
('bandainamcoent.com',      '18', 'Bandai Namco',    FALSE, 'curated'),
('tekken.com',              '18', 'Tekken',          FALSE, 'curated'),
('sega.com',                '18', 'SEGA',            FALSE, 'curated'),
('capcom.com',              '18', 'Capcom',          FALSE, 'curated'),
('konami.com',              '18', 'Konami',          FALSE, 'curated'),
('bungie.net',              '18', 'Bungie (Destiny)',FALSE, 'curated'),
('destiny2.com',            '18', 'Destiny 2',       FALSE, 'curated'),
('pathofexile.com',         '18', 'Path of Exile',   FALSE, 'curated'),
('dota2.com',               '18', 'Dota 2',          FALSE, 'curated'),
('csgo.com',                '18', 'CS:GO',           FALSE, 'curated'),
('counter-strike.net',      '18', 'Counter-Strike',  FALSE, 'curated'),
('overwatchleague.com',     '18', 'Overwatch',       FALSE, 'curated'),
('diablo4.com',             '18', 'Diablo IV',       FALSE, 'curated'),
('elderscrollsonline.com',  '18', 'ESO',             FALSE, 'curated'),
('warthunder.com',          '18', 'War Thunder',     FALSE, 'curated'),
('worldoftanks.com',        '18', 'World of Tanks',  FALSE, 'curated'),
('wargaming.net',           '18', 'Wargaming',       FALSE, 'curated'),
('tankionline.com',         '18', 'Tanki Online',    FALSE, 'curated'),
('ageofempires.com',        '18', 'Age of Empires',  FALSE, 'curated'),
('leagueoflegends.in',      '18', 'LoL',             FALSE, 'curated'),
('nexon.com',               '18', 'Nexon',           FALSE, 'curated'),
('maplestory.com',          '18', 'MapleStory',      FALSE, 'curated'),
('genshin.hoyoverse.com',   '18', 'Genshin Impact',  FALSE, 'curated'),
('honkaiimpact3.com',       '18', 'Honkai Impact',   FALSE, 'curated'),
('starrailstation.com',     '18', 'Honkai Star Rail', FALSE,'curated'),
('wuthering.kurogame.com',  '18', 'Wuthering Waves', FALSE, 'curated'),
('mobile-legends.net',      '18', 'Mobile Legends',  FALSE, 'curated'),
('moonton.com',             '18', 'Moonton',         FALSE, 'curated'),
('wildrift.leagueoflegends.com','18','LoL Wild Rift', FALSE,'curated'),
('codm.activision.com',     '18', 'CoD Mobile',      FALSE, 'curated'),
('bgmobile.eu',             '18', 'BGMI',            FALSE, 'curated'),
('battlegroundsmobileindia.com','18','BGMI',          FALSE,'curated'),
('chess.com',               '18', 'Chess.com',       FALSE, 'curated'),
('lichess.org',             '18', 'Lichess',         FALSE, 'curated'),
('ludo-king.com',           '18', 'Ludo King',       FALSE, 'curated'),
('8balltournament.com',     '18', '8 Ball Pool',     FALSE, 'curated'),
('miniclip.com',            '18', 'Miniclip',        FALSE, 'curated'),
('poki.com',                '18', 'Poki',            FALSE, 'curated'),
('coolmathgames.com',       '18', 'CoolMathGames',   FALSE, 'curated'),
('y8.com',                  '18', 'Y8 Games',        FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── ADS / TRACKING ── store under a new category or category 03 (reuse 03 as adware) ──
-- Using category '03' (Malware & Ransomware) since ads/trackers aren't a separate category.
-- Note: ads_blocked flag handles most ad blocking; these are high-risk ad networks.
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('doubleclick.net',         '03', 'Google Ads',      TRUE,  'curated'),
('googlesyndication.com',   '03', 'Google Ads',      TRUE,  'curated'),
('googleadservices.com',    '03', 'Google Ads',      FALSE, 'curated'),
('google-analytics.com',    '03', 'Google Analytics',FALSE, 'curated'),
('googletagmanager.com',    '03', 'Google Tag Mgr',  FALSE, 'curated'),
('amazon-adsystem.com',     '03', 'Amazon Ads',      TRUE,  'curated'),
('ads.twitter.com',         '03', 'Twitter Ads',     FALSE, 'curated'),
('ads.facebook.com',        '03', 'Meta Ads',        FALSE, 'curated'),
('scorecardresearch.com',   '03', 'comScore',        FALSE, 'curated'),
('quantserve.com',          '03', 'Quantcast',       FALSE, 'curated'),
('taboola.com',             '03', 'Taboola',         FALSE, 'curated'),
('outbrain.com',            '03', 'Outbrain',        FALSE, 'curated'),
('revcontent.com',          '03', 'RevContent',      FALSE, 'curated'),
('mgid.com',                '03', 'MGID',            FALSE, 'curated'),
('adroll.com',              '03', 'AdRoll',          FALSE, 'curated'),
('criteo.com',              '03', 'Criteo',          FALSE, 'curated'),
('criteo.net',              '03', 'Criteo',          TRUE,  'curated'),
('casalemedia.com',         '03', 'Index Exchange',  FALSE, 'curated'),
('rubiconproject.com',      '03', 'Rubicon',         FALSE, 'curated'),
('openx.net',               '03', 'OpenX',           FALSE, 'curated'),
('pubmatic.com',            '03', 'PubMatic',        FALSE, 'curated'),
('appnexus.com',            '03', 'AppNexus/Xandr',  FALSE, 'curated'),
('mopub.com',               '03', 'MoPub',           FALSE, 'curated'),
('inmobi.com',              '03', 'InMobi',          FALSE, 'curated'),
('moatads.com',             '03', 'Oracle Moat',     FALSE, 'curated'),
('adsymptotic.com',         '03', 'Adsymptotic',     FALSE, 'curated'),
('adcolony.com',            '03', 'AdColony',        FALSE, 'curated'),
('flurry.com',              '03', 'Flurry Analytics',FALSE, 'curated'),
('amplitude.com',           '03', 'Amplitude',       FALSE, 'curated'),
('mixpanel.com',            '03', 'Mixpanel',        FALSE, 'curated'),
('segment.io',              '03', 'Segment',         FALSE, 'curated'),
('segment.com',             '03', 'Segment',         FALSE, 'curated'),
('hotjar.com',              '03', 'Hotjar',          FALSE, 'curated'),
('fullstory.com',           '03', 'FullStory',       FALSE, 'curated'),
('mouseflow.com',           '03', 'Mouseflow',       FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── VPN / PROXY BYPASS (23) ───────────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('zenmate.com',             '23', 'ZenMate',         FALSE, 'curated'),
('browsec.com',             '23', 'Browsec',         FALSE, 'curated'),
('hoxx.com',                '23', 'Hoxx VPN',        FALSE, 'curated'),
('frigate.ru',              '23', 'Frigate',         FALSE, 'curated'),
('stealthvpn.net',          '23', 'StealthVPN',      FALSE, 'curated'),
('urbanvpn.com',            '23', 'Urban VPN',       FALSE, 'curated'),
('vpnbook.com',             '23', 'VPNBook',         FALSE, 'curated'),
('free-vpn.org',            '23', 'Free VPN',        FALSE, 'curated'),
('hola.org',                '23', 'Hola VPN',        FALSE, 'curated'),
('holavpn.com',             '23', 'Hola VPN',        FALSE, 'curated'),
('betternet.co',            '23', 'Betternet',       FALSE, 'curated'),
('vpngate.net',             '23', 'VPN Gate',        FALSE, 'curated'),
('vpnmentor.com',           '23', 'vpnMentor',       FALSE, 'curated'),
('vpnranks.com',            '23', 'VPNRanks',        FALSE, 'curated'),
('mullvad.net',             '23', 'Mullvad',         FALSE, 'curated'),
('azirevpn.com',            '23', 'AzireVPN',        FALSE, 'curated'),
('perfect-privacy.com',     '23', 'Perfect Privacy', FALSE, 'curated'),
('airvpn.org',              '23', 'AirVPN',          FALSE, 'curated'),
('boxpn.com',               '23', 'BoxPN',           FALSE, 'curated'),
('cactus-vpn.com',          '23', 'CactusVPN',       FALSE, 'curated'),
('proxysite.com',           '23', 'ProxySite',       FALSE, 'curated'),
('kproxy.com',              '23', 'KProxy',          FALSE, 'curated'),
('zfreez.com',              '23', 'zFreez',          FALSE, 'curated'),
('4everproxy.com',          '23', '4everproxy',      FALSE, 'curated'),
('croxy-proxy.com',         '23', 'CroxyProxy',      FALSE, 'curated'),
('proxfree.com',            '23', 'ProxFree',        FALSE, 'curated'),
('hidester.com',            '23', 'Hidester',        FALSE, 'curated'),
('anonymouse.org',          '23', 'Anonymouse',      FALSE, 'curated'),
('anonymox.net',            '23', 'anonymoX',        FALSE, 'curated'),
('filterbypass.me',         '23', 'FilterBypass',    FALSE, 'curated')
ON CONFLICT DO NOTHING;

-- ── Piracy / Illegal Streaming (05) ────────────────────────────────────────────
INSERT INTO dns.domain_blocklist (domain, category_id, app_name, is_cdn, source) VALUES
('torrentking.eu',          '05', 'TorrentKing',     FALSE, 'curated'),
('torrent9.ph',             '05', 'Torrent9',        FALSE, 'curated'),
('cpasbien.pe',             '05', 'CpaSBien',        FALSE, 'curated'),
('yggtorrent.re',           '05', 'YggTorrent',      FALSE, 'curated'),
('btetree.com',             '05', 'bteTree',         FALSE, 'curated'),
('rutracker.org',           '05', 'RuTracker',       FALSE, 'curated'),
('kinozal.tv',              '05', 'Kinozal',         FALSE, 'curated'),
('animefrenzy.net',         '05', 'AnimeFrenzy',     FALSE, 'curated'),
('9anime.to',               '05', '9Anime',          FALSE, 'curated'),
('kissanime.ru',            '05', 'KissAnime',       FALSE, 'curated'),
('animepahe.com',           '05', 'AnimePahe',       FALSE, 'curated'),
('gogoanime.io',            '05', 'GogoAnime',       FALSE, 'curated'),
('streamingcommunity.co',   '05', 'StreamingCommunity',FALSE,'curated'),
('altadefinizione.bond',    '05', 'AltaDefinizione', FALSE, 'curated'),
('filmstreamitalia.com',    '05', 'FilmStreamItalia',FALSE, 'curated'),
('seriesfree.org',          '05', 'SeriesFree',      FALSE, 'curated'),
('watchseries.ro',          '05', 'WatchSeries',     FALSE, 'curated'),
('flixhd.cc',               '05', 'FlixHD',          FALSE, 'curated'),
('lookmovie.ag',            '05', 'LookMovie',       FALSE, 'curated'),
('movierulz.com',           '05', 'MovieRulz',       FALSE, 'curated'),
('tamilblasters.it',        '05', 'TamilBlasters',   FALSE, 'curated'),
('tamilrockers.wc',         '05', 'TamilRockers',    FALSE, 'curated'),
('bolly4u.org',             '05', 'Bolly4u',         FALSE, 'curated'),
('filmywap.com',            '05', 'Filmywap',        FALSE, 'curated'),
('filmyzilla.com.co',       '05', 'Filmyzilla',      FALSE, 'curated')
ON CONFLICT DO NOTHING;
