apiVersion: v1
kind: Namespace
metadata:
  name: shield-prod
  labels:
    app.kubernetes.io/part-of: shield-platform
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: shield-dev
  labels:
    app.kubernetes.io/part-of: shield-platform
    env: dev
